<?php Tag::css('scaffold') ?>
<div class="comentar" id="comentar">
    <?php View::content(); ?>
    <h1>Editar</h1>    
    <?php echo Form::open(null, 'post', 'class="scaffold"') ?>
    <?php echo Form::hidden('usuario.id', null, $usuario->id)?>
    <label for="usuario_nombre" class="required">Nombre completo<em>*</em></label>
    <?php echo Form::text('usuario.nombre','placeholder="Escriba aqui su nombre completo" required="required"') ?>
    <label for="usuario_nick" class="required">Nombre de usuario <em>*</em></label>
    <?php echo Form::text('usuario.nick','placeholder="Escriba aqui su nombre de usuario" required="required"') ?>   
    <label for="usuario_web" class="required">Web</label>
    <?php echo FormHtml5::url('usuario.web','placeholder="¿Tienes un sitio web?"') ?>
    <label for="usuario_bio" class="required">Bio</label>
    <?php echo Form::textarea('usuario.bio','placeholder="Escribe algo sobre ti"') ?>
    <input type="submit" value="Enviar" />
    <?php echo Form::close() ?>    
</div>