<div id='logo-kumbia'><?php echo Html::img('default/kumbia.png', 'KumbiaPHP logo') ?></div>
<div id='info'>
    <h1>KumbiaPHP está listo para usarse</h1>
    <p>Esta es una primera app base para la adimistración de usuarios, roles, recursos, permisos y menús.</p>
    <p><?php echo Html::link('admin/', 'Ir a la zona de administración')?></p>
    <p><?php echo Html::link('usuario/recordar_clave/', 'Recordar clave')?></p>
</div>