<?php header('HTTP/1.1 401 Unauthorized'); ?>
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Acceso denegado</title>
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/style.css" />
    </head>
    <body>
        <div style="text-align: center; margin: 50px; font-size: 12pt; background-color: transparent; font-family: Lucida Grande, Verdana, Sans-serif;">
            <table align="center" id="content" style="background-color: #fff; border: #999 1px solid; padding: 10px 10px 6px 10px; width: 50%;">
                <tbody>
                    <tr>
                        <td style="width: 5%">
                            <a href="http://kuportal"><img src="<?php echo PUBLIC_PATH ?>img/site_logo.gif" alt="KuPortal"/></a>
                        </td>
                        <td>
                            <h1 style="font-size: 14pt; color: #990000; margin: 0 0 4px 0;">ERROR 401</h1>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?php View::content() ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>