<!doctype html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Administración</title>
        <?php echo Tag::css('jquery/login/screen'); ?>
        <?php echo Html::includeCss(); ?>
    </head>
    <body>
        <div id="cont">
            <div class="box lock"> </div>
            <div id="loginform" class="box form">
                <h2>Ingrese sus Credenciales <a href="" class="close">Close it</a></h2>
                <div class="formcont">
                    <fieldset id="signin_menu">
                        <span class="message" style="color: red"><?php echo $error_msj ?></span>
                        <form method="post" id="signin">
                            <p>
                                <label for="username">Usuario</label>
                                <input id="txt_login" name="txt_login" value="" title="username" class="required" tabindex="1" type="text">
                            </p>
                            <p>
                                <label for="password">Clave</label>
                                <input id="txt_password" name="txt_password" value="" title="password" class="required" tabindex="2" type="password">
                            </p>
                            <p class="clear"></p>
                            <a href="#" class="forgot">Recordar?</a>
                            <p class="remember">
                                <input id="signin_submit" value="Entrar" tabindex="3" type="submit">
                                <input id="cancel_submit" value="Cancelar" tabindex="4" type="button">
                                <input type="hidden" name='mode' value='auth_login' />
                            </p>
                        </form>
                    </fieldset>
                </div>
                <div class="formfooter"></div>
            </div>
        </div>

        <?php echo Tag::js('jquery/jquery.min') ?>
        <?php echo Tag::js('jquery/jquery.login') ?>
    </body>
</html>
